/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getItemAccess().getAlternatives(), "rule__Item__Alternatives");
					put(grammarAccess.getOperationAccess().getAlternatives_2(), "rule__Operation__Alternatives_2");
					put(grammarAccess.getBuiltinTypeAccess().getAlternatives(), "rule__BuiltinType__Alternatives");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getInparamAccess().getGroup(), "rule__Inparam__Group__0");
					put(grammarAccess.getOutparamAccess().getGroup(), "rule__Outparam__Group__0");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
					put(grammarAccess.getInterfaceAccess().getNsURIAssignment_3(), "rule__Interface__NsURIAssignment_3");
					put(grammarAccess.getInterfaceAccess().getItemsAssignment_4(), "rule__Interface__ItemsAssignment_4");
					put(grammarAccess.getOperationAccess().getNameAssignment_1(), "rule__Operation__NameAssignment_1");
					put(grammarAccess.getOperationAccess().getInsAssignment_2_0(), "rule__Operation__InsAssignment_2_0");
					put(grammarAccess.getOperationAccess().getOutsAssignment_2_1(), "rule__Operation__OutsAssignment_2_1");
					put(grammarAccess.getEventAccess().getNameAssignment_1(), "rule__Event__NameAssignment_1");
					put(grammarAccess.getEventAccess().getOutsAssignment_2(), "rule__Event__OutsAssignment_2");
					put(grammarAccess.getInparamAccess().getNameAssignment_1(), "rule__Inparam__NameAssignment_1");
					put(grammarAccess.getInparamAccess().getTypeAssignment_3(), "rule__Inparam__TypeAssignment_3");
					put(grammarAccess.getOutparamAccess().getNameAssignment_1(), "rule__Outparam__NameAssignment_1");
					put(grammarAccess.getOutparamAccess().getTypeAssignment_3(), "rule__Outparam__TypeAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleInterface();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
